### ISSUE TITLE
Correcting Wrong Answer

### ISSUE THREAD

**Issue by ahmedh7** [Ditectrev/AWS-Cloud-Practitioner-CLF-C01-Exam-Questions-Answers#2]
What does Amazon Elastic Beanstalk provide?
 A PaaS solution to automate application deployment. **(Correct)**
 A compute engine for Amazon ECS. **(Marked)**
 A scalable file storage solution for use with AWS and on-premises servers.
 A NoSQL database service.

[Question link](https://github.com/Ditectrev/AWS-Cloud-Practitioner-CLF-C01-Exam-Questions-Answers#what-does-amazon-elastic-beanstalk-provide)

**Comment by danieldanielecki** [comment]
@ahmedh7 100% correct, fixed in https://github.com/Ditectrev/AWS-Cloud-Practitioner-CLF-C01-Exam-Questions-Answers/commit/17c70524274f4e57215ce14ead4bd76d9db7cba6
